### ISSUE TITLE
Terms and definitions

### ISSUE THREAD

**Issue by ellislau** [darwinrlo/the-glendale-project#1]
Utility - How are we defining this? Some unit of happiness? An act of lying might have unknown consequences, but if the lying itself makes me unhappy, does it have negative utility?

Uncompromisable moral value - I'm not sure that "uncompromisable" or "infinite-weighted con" are appropriate. I would consider compromising a moral value to have some negative utility, but not infinite. I'm also not sure what contexts would involve morals that are considered uncompromisable.

**Comment by darwinrlo** [comment]
> Uncompromisable moral value - I'm not sure that "uncompromisable" or "infinite-weighted con" are appropriate. I would consider compromising a moral value to have some negative utility, but not infinite. I'm also not sure what contexts would involve morals that are considered uncompromisable.

I have included a proof that there is no such thing as an uncompromisable moral value. So my impression is that we agree.

> Utility - How are we defining this?

Ah, good question. Let me get back to you on this. To give you a hint, the definition is going to involve a large system of constraints. :-)

**Comment by darwinrlo** [comment]
I don't really want discussion to block on this. Here's a simple way to put it. Given two possible outcomes a and b, a has a higher utility than b if you would trade b for a. This applies to sets of outcomes too. Given two sets of outcomes A and B, Utility(A) > Utility(B) iff you would trade B for A.

I don't think we need a notion for absolute utility since we're trying to achieve the greatest utility, no matter its absolute value.

**Comment by ellislau** [comment]
That abstraction for utility works for me.

**Comment by darwinrlo** [comment]
We may run into a challenge when we try to compute expected utility -- that is, the product of the utility of an outcome and the probability of the outcome -- but we can take that on as it arises. I believe you have the intuition now.
